### ISSUE TITLE
Make sure all issues from previous sprint are reviewed

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#124]
Issues from sprint 21 that were completed but didn't get through entire review process: 
- [x] ~~[Terra Ref tutorial time zone conversions](https://github.com/terraref/tutorials/issues/196), @MagicMilly~~ This was already done and I hadn't noticed, thanks Emily! 
- [ ] [Split up BioCro vignettes](https://github.com/danforthcenter/sentinel-detection/issues/87), @dlebauer (during one on one)
- [x] [Terra Ref VICE app instructions/prereq rework](https://github.com/terraref/tutorials/issues/220), need to find reviewer (done by David Nov 13)
- [ ] [Hiring OSF page](https://github.com/az-digitalag/organization/issues/117), @Chris-Schnaufer
