### ISSUE TITLE
KR: Finish website and publish with new domain

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#185]
[Old UA website](https://datascience.cals.arizona.edu/) to [new blogdown website with Academic theme](https://quizzical-perlman-731692.netlify.com/). Get [the website repo](https://github.com/az-digitalag/group-website) locally and can edit and view within RStudio. 

Possible content to add/move: 
- [ ] Group mission (vision has already been moved)
- [ ] **What We Do** section; do we want this to be static, non-clickable cards still? 
- [x] **Projects** page; have clickable cards on main page, with four separate pages for each project? 
- [x] **People** page; maybe model this after https://www.weecology.org/ people section? 
- [x] **Services** section has a lot of overlap with **What We Do**, how to combine and present? 
- [x] **News** posts will move to a **Recent Posts** section, with links to each post
    * we can retain the same links as on the drupal website if we use the 'alias' (I think) on our posts
- [x] Add **Publications** section
- [ ] Add **Funding** section for grants we're on/associated with? 
- [ ] Update **Contacts** section
- [ ] **css** design elements from UA Hugo Theme 
- [ ] **dns** use domain datascience.cals.arizona.edu
- [ ] get google Analytics code from CCT
- [ ] * apply for open source plan that provides custom domain and more useful features https://www.netlify.com/legal/open-source-policy/

Resources: 
- [How to create initial website with blogdown and Hugo Academic](https://www.kevinzolea.com/post/blogdown/creating-a-website-with-the-academic-theme-in-blogdown/)
- [blogdown book](https://bookdown.org/yihui/blogdown/)
- [Using widgets](https://www.themillerlab.io/post/website-development-using-r/) (second half of post)
- [Example lab site](https://www.themillerlab.io/)
- [Example lab site](https://www.weecology.org/)

**Comment by KristinaRiemer** [comment]
Proposed website organization for MVP of new website: 

(ordered sections)
1. First section will have short motto thing ("We want to help you do your science"), then vision and mission 
    - Remove "Interests" section
    - Update email contact
2. Services section w/ 4 static cards that have "What We Do" content
3. **complete** People section 
4. Projects section w/ 4 clickable cards that go to pages that include what's currently in cards on old website
5. **complete** Posts section

Get rid of these current sections: Skills, Gallery, Contact, Talks, Publications (2x), Popular Topics

**Comment by KristinaRiemer** [comment]
Part of [the followup on OLS](https://github.com/AgPipeline/issues-and-projects/issues/151https://github.com/AgPipeline/issues-and-projects/issues/151) is including drone pipeline documentation in the Projects section for that project.

**Comment by KristinaRiemer** [comment]
Projects could also have a direct link to how to contribute to them.

**Comment by dlebauer** [comment]
no longer necessary as we move (back) to Drupal quickstart
