### ISSUE TITLE
AZ Carbon Stores / David Moore

### ISSUE THREAD

**Issue by Aariq** [az-digitalag/organization#1850]
Epic for the AZ carbon stores project with David Moore and Charlie Devine.  Main repo here: https://github.com/cct-datascience/SW_Biomass

- [ ] Download all the datasets
  - [ ] https://github.com/cct-datascience/SW_Biomass/issues/9
- [ ] https://github.com/cct-datascience/SW_Biomass/issues/7
- [ ] https://github.com/cct-datascience/SW_Biomass/issues/4
- [ ] https://github.com/cct-datascience/SW_Biomass/issues/5
- [ ] https://github.com/cct-datascience/SW_Biomass/issues/6

**Comment by Aariq** [comment]
OOps, duplicate of #1800
