### ISSUE TITLE
February 2024 Workshop Task List

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#1877]
-   **Title:** Customizable Resumes with R Tools
-   **Lead Instructor:** Kristina
-   **Helpers:** Eric?
-   **Date:** February 28, 2024
-   **Target Audience:** folks with some R experience
-   **Description:**

# Tasks

More detailed instructions for specific steps here: <https://cct-datascience.github.io/group-procedures/workshops.html>

## Organizing the event

- [x] Identify presenter, title, description
- [ ] Draft PR with notes or links to materials in [workshop-wednesdays repo](https://github.com/cct-datascience/workshop-wednesdays)
- [x] Create a Zoom meeting with registration ([instructions & settings](https://cct-datascience.github.io/group-procedures/workshops.html#creating-a-template-for-workshop-zoom-meetings))
- [x] Write up announcement and record on the [Workshops HackMD](https://hackmd.io/-hSaZbuzQI-gAPP3pASvRw)
- [ ] Advertise
  - [x] Add an event to the [group website workshops page](https://datascience.cals.arizona.edu/workshops)
  - [x] Add to Data Science Institute calendar <https://datascience.arizona.edu/calendar>
  - [x] Include announcement in the next mailing list email
  - [x] Announce on resBazAZ and UA Data Science Slack

## Before workshop

- [ ] Provide homework / background reading as appropriate (installation, references, etc.)
- [ ] Send out reminders

## Follow-up tasks

- [ ] Merge PR to [CALS-workshops repo](https://github.com/cct-datascience/CALS-workshops) 
- [ ] Post Zoom recording to YouTube
- [ ] Update the event page on the group website
  - [ ] Add links to recording and materials
  - [ ] Check the "Archive" checkbox
- [ ] Follow up email with post-workshop survey and invite participants to office hours
- [ ] Download Zoom reports and add registration information to [this sheet](https://docs.google.com/spreadsheets/d/1SU8Wtx7Ku1IMv8DOAU-37E12-AZP0CjnRy1vPSkmNGQ/edit#gid=0)
- [ ] Add new registrants (who opted in) to the listserv in myEmma

**Comment by KristinaRiemer** [comment]
Places to advertise: 
- [x] Group listserv
- [x] UA DS Slack
- [x] ResBaz Slack
- [x] DSI events page
- [x] Data Drip
- [x] CALES grad students via Jia Hu
- [x] R users listserv via Jeff Oliver
- [x] DSAs (Lia & Christian)
