### ISSUE TITLE
April 2024: Wrangling larger-than-memory data in R

### ISSUE THREAD

**Issue by diazrenata** [az-digitalag/organization#1969]
-   **Title:** Wrangling larger-than-memory data in R with arrow and duckdb
-   **Lead Instructor:** Renata
-   **Helpers:**
-   **Date:** April 24, 2024
-   **Target Audience:** R users working with large datasets, not already using a formal database
-   **Description:** Data wrangling in R is powerful, but becomes challenging when your dataset is too big for R to open all at once. This workshop will cover new tools that will let you continue to use familiar data wrangling tools in R with larger-than-memory data, including the `arrow` and `duckdb` packages. Participants should be familiar with R. Familiarity with the tidyverse, and/or having an example dataset in mind, are both beneficial but not necessary!

# Tasks

More detailed instructions for specific steps here: <https://cct-datascience.github.io/group-procedures/workshops.html>

## Organizing the event

- [x] Identify presenter, title, description
- [x] Draft PR with notes or links to materials in [workshop-wednesdays repo](https://github.com/cct-datascience/workshop-wednesdays)
- [x] Create a Zoom meeting with registration ([instructions & settings](https://cct-datascience.github.io/group-procedures/workshops.html#creating-a-template-for-workshop-zoom-meetings)) https://arizona.zoom.us/meeting/register/tZctcO2qpzIiEtGhUgOfdFk8Xu4SbBo_OYAz
- [x] Write up announcement and record on the [Workshops HackMD](https://hackmd.io/-hSaZbuzQI-gAPP3pASvRw)
- [x] Advertise
  - [ ] Add an event to the [group website workshops page](https://datascience.cals.arizona.edu/workshops)
  - [ ] Add to Data Science Institute calendar <https://datascience.arizona.edu/calendar>
  - [ ] Include announcement in the next mailing list email
  - [ ] Announce on resBazAZ and UA Data Science Slack

## Before workshop

- [x] Provide homework / background reading as appropriate (installation, references, etc.)
- [x] Send out reminders

## Follow-up tasks

- [x] Merge PR to [CALS-workshops repo](https://github.com/cct-datascience/CALS-workshops) 
- [ ] Post Zoom recording to YouTube
- [x] Update the event page on the group website
  - [x] Add links to recording and materials
  - [ ] Check the "Archive" checkbox
- [x] Follow up email with post-workshop survey and invite participants to office hours
- [x] Download Zoom reports and add registration information to [this sheet](https://docs.google.com/spreadsheets/d/1SU8Wtx7Ku1IMv8DOAU-37E12-AZP0CjnRy1vPSkmNGQ/edit#gid=0)
- [ ] Add new registrants (who opted in) to the listserv in myEmma
