### ISSUE TITLE
Review meta analysis 

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#201]
* [x] read and comment
* [x] review code and data
* [x] write up summary
