### ISSUE TITLE
ggplot2 series session 2: Data Communication

### ISSUE THREAD

**Issue by diazrenata** [az-digitalag/organization#2125]
-   **Title:**
-   **Lead Instructor:**
-   **Helpers:**
-   **Date:**
-   **Target Audience:**
-   **Description:**

# Tasks

More detailed instructions for specific steps here: <https://cct-datascience.github.io/group-procedures/workshops.html>

## Organizing the event

- [ ] Identify presenter, title, description
- [ ] Draft PR with notes or links to materials in [workshop-wednesdays repo](https://github.com/cct-datascience/workshop-wednesdays)
- [ ] Create a Zoom meeting with registration ([instructions & settings](https://cct-datascience.github.io/group-procedures/workshops.html#creating-a-template-for-workshop-zoom-meetings))
- [ ] Write up announcement and record on the [Workshops HackMD](https://hackmd.io/-hSaZbuzQI-gAPP3pASvRw)
- [ ] Advertise
  - [ ] Add an event to the [group website workshops page](https://datascience.cals.arizona.edu/workshops)
  - [ ] Add to Data Science Institute calendar <https://datascience.arizona.edu/calendar>
  - [ ] Include announcement in the next mailing list email
  - [ ] Announce on resBazAZ and UA Data Science Slack

## Before workshop

- [ ] Provide homework / background reading as appropriate (installation, references, etc.)
- [ ] Send out reminders

## Follow-up tasks

- [x] Merge PR to [CALS-workshops repo](https://github.com/cct-datascience/CALS-workshops) 
- [ ] Post Zoom recording to YouTube
- [ ] Update the event page on the group website
  - [ ] Add links to recording and materials
  - [ ] Check the "Archive" checkbox
- [ ] Follow up email with post-workshop survey and invite participants to office hours
- [x] Download Zoom reports and add registration information to [this sheet](https://docs.google.com/spreadsheets/d/1SU8Wtx7Ku1IMv8DOAU-37E12-AZP0CjnRy1vPSkmNGQ/edit#gid=0)
- [ ] Add new registrants (who opted in) to the listserv in myEmma
