### ISSUE TITLE
Update SPARCd app with 2 more fixes and make release

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#2167]
**Task to do**
Fix two outstanding issues and make a new release

**Reason**
Tackling two highest remaining issues

**Result**
A new release is made with the new features

**Steps to take**
- [ ] Confirm a failure message is shown when uploads fail
- [ ] Add a success message when uploads succeed
- [ ] Add a cancel button to stop queries
- [ ] Build a new release
- [ ] Test new release
