### ISSUE TITLE
Prepare for and Participate in Data Science for Career Changers Panel on 7/15

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#236]
**Task to do**
Prepare for second Flatiron School alumni panel, this time on what it's like to work in data science and discussing your current role. 

**Reason**
This second panel will offer a better opportunity to discuss my role in more detail and provide outreach about our team and work. 

**Result**
More practice with public speaking, especially when discussing our team and what we do. Provide outreach about our work and share our website and twitter. 

**Steps to take**
- [x] Watch original video and take note of how I can improve. 
    - Main Improvement: Do not sit in swivel chair. 
- [x] Attend Webinar practice on Monday, 7/13
~Share original video with some (or all) team members to see if they'd like to watch and provide feedback.~ 
~Practice answering questions with at least one other person before the panel~
- [x] Record myself answering practice questions
- [x] Panel on Wednesday, 7/15

**Comment by MagicMilly** [comment]
Panel finished 7/15. Have connected with more alumni to answer questions and network; one attendee in particular was interested in agricultural data science.
