### ISSUE TITLE
Edit Twitter Guidelines on OSF Pages

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#247]
**Tasks to do**
Using what we learned from Caroline and other experiences:
- [ ] Determine our specific brand and / or message we want to convey
- [x] More specific guidelines and timelines for certain activities (e.g. all retweets must include a comment with at least one tag)
- [x] Scheduling, length of time, and responsibilities for *volunteer* Twitter Curators
- [x] Decide or brainstorm ideas for how to streamline process of David (or just one other person?) approving tweets before they go out into the world
- [ ] Set up Twitter Analytics
- [x] Discuss the above issues, create shared document for asynchronous discussion, or send out survey to team

**Future**: add Twitter stream to website

**Reasons & Results**
- Become more involved in the science, data science, and digital ag communities on Twitter, which will hopefully lead to fruitful, future collaborations and relationships
- More networking, learning, teaching, and discussion opportunities
- Greater visibility for our group and its mission and vision
- More opportunities to work on promoting and participating in the discussion of more inclusivity in STEM
- Promote our projects, engage with future contributors

**Comment by MagicMilly** [comment]
- Results of [survey](https://docs.google.com/spreadsheets/d/1Td40VxFlHjnehIu2vKdHCOABvPGadIO6EfCCo5Qm5oY/edit?usp=sharing)
- Shared Google [doc](https://docs.google.com/document/d/1wo9XEEyeHE-nDSL39Hw6vY0-Q-YU3e-8ZOr7eRETPLk/edit?usp=sharing) discussing results and proposed guidelines

**Comment by MagicMilly** [comment]
- The guidelines for the Twitter Curator (TC) have been added to [OSF](https://osf.io/tzmhp/wiki/Public%20Communications/) after surveying the team and drafting guidelines
- Re: the unchecked boxes
    - Our Team's mission is our brand, which we will emphasize more with our Twitter activity and new website
    - Currently David is able to see the group's Twitter Analytics - still need to determine whether all team members can see this. Analytics will be more important once we've increased our activity and engagement. 

Follow up ticket #257 for first Sprint
