### ISSUE TITLE
Set up one project on OSF page to explore different functionalities

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#249]
**Tasks to do**
- [x] Choose guinea pig project to add to our OSF page (maybe David's Dryad publication?)
- [ ] Go through steps of adding a project while documenting process, incorporate integrations for storage, code, citation, etc.

**Additional but Unrelated**
- [ ] Update Sprint Meeting descriptions and protocols - see sprint [notes](https://hackmd.io/ih-qR2B6RJ221MJEFeEqcA)

**Reasons**
- Determine and document process for adding projects
- Find out exactly what kinds of projects can be added (in progress, planning, already published, etc.), if there's a limit on what we can add or link to, what makes the most sense and is the easiest way for others to explore the details of our work

**Result**
Discover capabilities and limitations of adding projects to OSF and if this is a good choice for the group

[Example](https://osf.io/vgt3x/) of an OSF page with multiple, linked projects and GDrive integrations

**Comment by MagicMilly** [comment]
Absorbing this OLS [ticket](https://github.com/AgPipeline/issues-and-projects/issues/151) about documentation for the pipeline as part of the migration of projects to the new website, and then pointing to our OSF project pages for more details.

**Comment by MagicMilly** [comment]
Follow-up action items will be in new ticket #260

**Comment by MagicMilly** [comment]
- Demo OSF [Project](https://osf.io/42fzy/?view_only=d74904694eda413e92fd2700931a7e0a)
- Have taken notes on process, still need to add documentation to Group OSF (added to follow-up ticket #260)
- Follow-up ticket also includes updating new Sprint Planning procedures
