### ISSUE TITLE
NEON fastq meta data pull script

### ISSUE THREAD

**Issue by rbartelme** [az-digitalag/organization#255]
- [x] Get NEON API key

- [x] Code to pull metagenome metadata

- [x] Code to pull amplicon metadata

**Comment by rbartelme** [comment]
The [code](https://github.com/rbartelme/NEON_metagenomics/blob/master/neon_query/microbe_metadata.R) contains all of the above elements, issue #266 has more details on next steps.

In short:

I'll file a new issue for the next steps, which will involve moving the code to the new cluster and pulling the data into a new directory structure.
