### ISSUE TITLE
First Sprint as Twitter Curator

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#257]
**Tasks to do**

As outlined in the new Twitter [guidelines](https://osf.io/tzmhp/wiki/Public%20Communications/):

For Sprint 40:

- [x] at least one tweet for the week of August 3
- [x] Review Followers / Following
- [x] at least one tweet for the week of August 10
- [x] Link to Twitter activity in comments
~To discuss: should the TC announce and introduce themselves?~ Should be moved into the future, when we're more active 

**Reason**
Improve group visibility with more organized social media activity

**Comment by MagicMilly** [comment]
- First week's [retweet with comment](https://twitter.com/DigitalAgGroup/status/1291875569223622656?s=20) about PEG collaborator's ESA talk 
- Second week's [tweet](https://twitter.com/DigitalAgGroup/status/1294010332029923328?s=20) about the upcoming #ODDPIG kickoff meeting
