### ISSUE TITLE
Next steps for applying to CS&S Event Fund

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#258]
**Tasks to do**
- [x] Follow-up email to Larissa
- [x] Decide if we have the time and enthusiasm to continue
- [x] If so, will add more follow-up actions to this ticket

**Comment by MagicMilly** [comment]
- [ ] Prepare and send proposal to David / Fatemah
    - [ ] Scope of work
    - [ ] Detailed budget
