### ISSUE TITLE
Next steps for adding projects to and updating OSF Pages

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#260]
Follow-up action items after completing issue #249 

**need to clarify specific tasks to complete this ticket**

**Tasks to do**
- [x] Update Sprint Planning Meeting protocols
- [x] Figure out how to integrate with Projects section on new group website (maybe just a link for more details) - will work on during Hackathon Day #261  
- [ ] Add notes and suggestions to documentation on Group OSF

**Reasons**
- Promote open science by example
- Make it easier for others to find all elements of our projects, to either follow our progress, cite our work, contribute, and/or collaborate
- Make it easier for group members to see what others are working on
- Have a central location with links to resources, tutorials, data, etc. 

**Updated**
- [ ] Start TERRA-REF OSF project to send with our CS&S proposal, as an example of what we can provide for the hackathon participants

**Comment by MagicMilly** [comment]
Updated Sprint Meeting guidelines on [OSF](https://osf.io/tzmhp/wiki/Sprint%20Meetings/)

**Comment by MagicMilly** [comment]
Bumping to next Sprint. My goal is to finish this soon (at least by the end of the week) to include with our CS&S proposal.

**Comment by MagicMilly** [comment]
Clearing the points estimate on this ticket and closing due to being too vague and including issues/tasks that should be separated and defined more clearly
