### ISSUE TITLE
Add three different ways to access TERRA-REF trait data to the OSF page 

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#280]
**Reason**
Create a TERRA-REF OSF page for an introduction of working with the data (starting with trait data), with programmers/analysts/researchers/learners of various skill levels in mind. 

**Tasks**
- [ ] Start with a section to help users decide which method is most appropriate for them
- [x] Add Dryad data with easy download for beginners
- [x] Instructions in wiki for beginner download
- [x] Add `R` code for querying data for `R` programmers
- [x] Include and link to Kristina's tutorial for `R` code
- [x] For more advanced learners, include and link to instructions for connecting to betydb using Docker and PyCharm
- [ ] In wiki, include prerequisites for each method 
- [ ] In wiki, also include resources to learn and read more about the different prerequisites (e.g. SQL statements)

**Desired Result**
Have three methods for accessing data and documentation for each on the Using TERRA-REF Data [OSF page](https://osf.io/wuj42/)

**Comment by MagicMilly** [comment]
Do not have a public link to the OSF page yet, but I added three wiki pages with the minimum viable information to access TERRA-REF data via download (beginner), R and RStudio, and Docker and SQL (advanced). Next ticket will include more information about prerequisites and links to resources appropriate for each level.
