### ISSUE TITLE
Add DIAG info to University of Arizona Cyberinfrastructure and Research Support document

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#336]
**Task to do**

Add description of our group to the UACRSD

**Reason**
Let others know that we are here

**Result**

Section on our group

**Steps to take**

* [x] Write section for our group to be added to this document https://docs.google.com/document/d/1EMMMm3WCTCcYEP1_iRLS4l0dys7z0uL5i39qIzcYxgY/edit#heading=h.xiy4g5g2w3p7
* [x] Assign to David to review and add to the doc
* [ ] Can also send it to CALS Faculty Resources

**Comment by jessicaguo** [comment]
Here is a draft: https://docs.google.com/document/d/16a0L8Ue1nYbJFDOOoKQWfcKY0Kr7o7sRxhLtBaWaR-w/edit

Needs to be updated with links to website and new mission/vision

**Comment by dlebauer** [comment]
This has been completed https://docs.google.com/document/d/1EMMMm3WCTCcYEP1_iRLS4l0dys7z0uL5i39qIzcYxgY/edit#heading=h.xiy4g5g2w3p7

We should probably also add our content somewhere here: https://research.cals.arizona.edu/
