### ISSUE TITLE
Office hours: Write up an announcement

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#395]
Draft: https://osf.io/h9vqt/wiki/home/

Scratch space: https://hackmd.io/@julianp-diag/SyWf9FZM_

## TODO

- [ ] Get feedback from @dlebauer and others
- [ ] Make OSF page public
- [ ] In email replace the gather.town text with a link to the DIAG Office Hours OSF page for latest teleconference venue:

>  _**Where:** ResBaz gather.town_
> _(Note: This gather.town collaborative space is hosted by Research Bazaar Arizona, a grass-roots community of practice focused on data intensive research.)_

... replaced with this:

> Check the [DIAG Office Hours OSF page](https://osf.io/h9vqt/wiki/home/?view_only=761498c019434b2babda38efc55d8f85) for the current venue/teleconference details

**Comment by julianpistorius** [comment]
Waiting for feedback from Kristina.
