### ISSUE TITLE
JP: Gantry Pipeline at UA

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#40]
## Key Results

- [x] A working pipeline on a small scale #29
- [x] Create virtual machines for UA Pipeline #41
- [ ] Automated deployment of basic pipeline #44
- [ ] Successful run of test data through system #45
- [ ] Processing season's data in real time with accurate results #46

**Comment by julianpistorius** [comment]
No longer relevant.
