### ISSUE TITLE
Meet with Rosa about DPP

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#406]
## TODO

- [x] Introduce Julian to Rosa (@Chris-Schnaufer)
- [x] Julian to respond with when2meet poll
- [x] Julian to set up meeting once Rosa & Chris have responded to when2meet
- [x] Meet (Wednesday, March 10⋅13:00 – 13:50)
- [x] Summarize

## Discuss

- How is the DE working for her?
- What problems does she run into?
- What could be improved?
- Is she using WebODM?

**Comment by julianpistorius** [comment]
Asked @Chris-Schnaufer to make introductions.

**Comment by Chris-Schnaufer** [comment]
Sent introduction email to Rosa and Julian March 4, 2021

**Comment by julianpistorius** [comment]
Meeting Wednesday, March 10⋅13:00 – 13:50
