### ISSUE TITLE
(KR) Automated deployment of basic pipeline

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#44]
Proposed solution: Nomad configuration.

Benefits:

- Manage and collaborate on configuration in GitHub
- Continuous integration
- Continuous delivery
- Canary/blue-green deployments
- Keep pipeline healthy with autopilot

Steps:

- [x] Nomad proof-of-concept https://github.com/terraref/terraref-terraform/issues/8
- [x] Deploy a Nomad cluster to OpenStack
- [x] Test pipeline with sample data set #52 
- [x] Demo & review proof-of-concept with team #53
- ~[ ] Iteration 2 of automated pipeline #54 (to incorporate suggestions and improvements)~
- ~[ ] Test pipeline with larger data set #55~

Related:

- [x] Makeflow Proof-of-Concept #102
