### ISSUE TITLE
Test pipeline with sample data set

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#52]
## Stage 1

Deploy Nomad jobs for every component of the processing pipeline:

- [x] Clowder (Use official Clowder Docker image instead of my hacked one)
- [x] Mongo
- [x] RabbitMQ
- [x] Elasticsearch
  - [x] Failing. Figure out why.

Estimate: 3 hours

## Stage 2

- [x] Wire stack together with Fabio load balancer
  - [x] Mongo
  - [x] Clowder
  - [x] Elasticsearch
  - [x] RabbitMQ

Estimate: 3 hours

## Stage 3

See: https://github.com/az-digitalag/organization/issues/29

- [x] Start an extractor
- [x] Upload a raw file & metadata
- [x] Confirm that the extractor worked and the data was processed correctly

Estimate: 3 hours

## Notes

Keep in mind what will be required for the Drone Pipeline as well: 

- https://osf.io/4t62q/
- https://osf.io/fcn5s/

**Comment by dlebauer** [comment]
Similar to https://github.com/az-digitalag/organization/issues/29 but with batch jobs / scaling and using Nomads

**Comment by julianpistorius** [comment]
@dlebauer See below:

![Screen Shot 2019-09-09 at 10 22 59](https://user-images.githubusercontent.com/742633/64552493-35e7a880-d2ec-11e9-91dc-a4537ab636cb.png)
![Screen Shot 2019-09-09 at 10 23 18](https://user-images.githubusercontent.com/742633/64552494-35e7a880-d2ec-11e9-811b-f37db2f428c1.png)
![Screen Shot 2019-09-09 at 10 23 44](https://user-images.githubusercontent.com/742633/64552495-36803f00-d2ec-11e9-8c65-0a3695d1285d.png)

**Comment by julianpistorius** [comment]
@dlebauer:

This is the Nomad job for Clowder:

https://github.com/julianpistorius/terraref-terraform/blob/9966398a0c5649ee3a57ed61804bac9d2ce4bc86/nomad-test/pipeline-setup-example.nomad

And this is the batch job to download and clean the data, upload it, and thereby kick off the extraction process:

https://github.com/julianpistorius/terraref-terraform/blob/9966398a0c5649ee3a57ed61804bac9d2ce4bc86/nomad-test/pipeline-setup-example.nomad

**Comment by dlebauer** [comment]
Thanks!
