### ISSUE TITLE
JP: Stabilize existing systems

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#57]
## Key Results

- [ ] Welsch containers and volumes moved to a new VM #58
- [ ] Database replicated to single local instance #59
- [ ] Monitoring for failing containers in place #60

## Misc tasks

- [x] URGENT: Handle Welsch backup volume getting full #74
- [x] Provide access to Welsch BETYdb for Kristina and Kimberly #75

**Comment by Chris-Schnaufer** [comment]
Closing as completed
