### ISSUE TITLE
(KR) Document - How TERRA REF works

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#62]
- [x] Read the TERRA REF documentation #64 
- [ ] Make notes (e.g. interesting, relevant, questions, out of date, clarifications needed, can be expanded) #65
- [ ] Update with relevant things related to the infrastructure work we've been doing at UA #67
