### ISSUE TITLE
(KR) Design docs

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#63]
- [ ] Document UA infrastructure work (initially to help new hire) #67 
- [ ] Create a human-readable index and table of contents for the shared Google Drive #68 
- [ ] Architecture diagram for UA Pipeline #103

**Comment by julianpistorius** [comment]
No longer relevant.
