### ISSUE TITLE
(KR) Hire new person

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#69]
- [x] Create a screening matrix based on Job Description #71
- [x] Make short list of candidates #70
- [ ] Screen short list of candidates #94
- [ ] Interview screened candidates #95

**Comment by dlebauer** [comment]
Hired and completed!
